import * as React from "react";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";
import CssBaseline from "@mui/material/CssBaseline";
import TextField from "@mui/material/TextField";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import Link from "@mui/material/Link";
import Grid from "@mui/material/Grid";
import Box from "@mui/material/Box";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import Typography from "@mui/material/Typography";
import Container from "@mui/material/Container";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Paper } from "@mui/material";
import { useNavigate, Link as Domlink } from "react-router-dom";
import { getqrcode, setupmfa, userLogin } from "../Service";
import swal from "sweetalert";

function Copyright(props) {
  return (
    <Typography
      variant="body2"
      color="text.secondary"
      align="center"
      {...props}
    >
      {"Copyright © "}
      <Link color="inherit" href="https://mui.com/">
        Your Website
      </Link>{" "}
      {new Date().getFullYear()}
      {"."}
    </Typography>
  );
}

const theme = createTheme();
const loginstyle = {
  padding: 20,
  height: "100vh",
  width: 500,
  margin: "20px auto",
};
export default function MfaSetup() {
  const navigate = useNavigate();
  const [Qrcode, Setqrcode] = React.useState();

  React.useEffect(() => {
    {
      getqrcode()
        .then(({ data }) => {
          console.log(data);
          Setqrcode(data.qrcode);
          //  localStorage.setItem("token", data.token);
          //  navigate("/mfasetup");
        })
        .catch((err) => {});
    }
  }, []);
  const handleSubmit = (event) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const body = {
      otp: data.get("otp"),
    };
    console.log(body);
    setupmfa(body)
      .then(({ data }) => {
        console.log(data);
        if (data.verified == false) {
          swal("Oops!", "Code is not valid!", "error");
        } else {
          localStorage.setItem("token", data.token);
          navigate("/dashboard");
        }
      })
      .catch((err) => {
        swal("Oops!", "Code is not valid!", "error");
      });
  };

  return (
    <>
      <Grid>
        <Paper elevation={10} style={loginstyle}>
          <Grid
            sx={{
              display: "flex",
              justifyContent: "center",
              marginBottom: 5,
            }}
          >
            <h2>MFA Authentication Setup</h2>
          </Grid>
          <Grid>
            <Typography variant="h6" gutterBottom>
              Step 1: Scan Barcode
            </Typography>
            <Typography>
              Use your authenticator app to scan the barcode below:
            </Typography>
            <Grid
              justify="flex-end"
              alignContent="center"
              sx={{ marginLeft: 16 }}
            >
              <img src={Qrcode} width="200" height="220"></img>
            </Grid>
            <Typography variant="h6">
              Step 2: Verify Code Once your app is configured
            </Typography>
            <Typography>
              {" "}
              enter the six-digit security code generated by your app to verify
              and enable multi factor authentication:
            </Typography>
            <Box
              component="form"
              onSubmit={handleSubmit}
              noValidate
              sx={{ mt: 1 }}
            >
              <TextField
                margin="normal"
                required
                fullWidth
                id="otp"
                label="Security Code"
                name="otp"
                autoFocus
              />

              <Button
                type="submit"
                fullWidth
                variant="contained"
                sx={{ mt: 3, mb: 2 }}
              >
                Submit
              </Button>
            </Box>
          </Grid>
        </Paper>
      </Grid>
    </>
  );
}
